=== NHSDigital/integration-adaptor-gp2gp/service/src/test/resources/mim/Schemas/RCMR_IN030000UK06.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:hl7-org:v3" elementFormDefault="qualified" xmlns:hl7="urn:hl7-org:v3" xmlns="urn:hl7-org:v3">
   <xs:annotation>
      <xs:documentation>Generated using schema builder version: 1.21p12 and DynamicMifToXSD.xsl version: 1.3</xs:documentation>
   </xs:annotation>
   <xs:include schemaLocation="../dt/datatypes.xsd"/>
   <xs:include schemaLocation="../voc/voc.xsd"/>
   <xs:include schemaLocation="UKCT_MT120501UK03.xsd"/>
   <xs:include schemaLocation="UKCT_MT120301UK02.xsd"/>
   <xs:include schemaLocation="UKCT_MT120901UK01.xsd"/>
   <xs:include schemaLocation="UKCT_MT121001UK01.xsd"/>
   <xs:include schemaLocation="MCCI_MT010101UK12.xsd"/>
   <xs:include schemaLocation="MCAI_MT040101UK03.xsd"/>
   <xs:include schemaLocation="RCMR_MT030101UK04.xsd"/>
   <xs:element name="RCMR_IN030000UK06" type="RCMR_IN030000UK06.Message"/>
   <xs:complexType name="RCMR_IN030000UK06.Message">
      <xs:sequence>
         <xs:element name="id" type="II" minOccurs="1" maxOccurs="1"/>
         <xs:element name="creationTime" type="TS" minOccurs="1" maxOccurs="1"/>
         <xs:element name="versionCode" type="CS" minOccurs="1" maxOccurs="1"/>
         <xs:element name="interactionId" type="II" minOccurs="1" maxOccurs="1"/>
         <xs:element name="processingCode" type="CS" minOccurs="1" maxOccurs="1"/>
         <xs:element name="processingModeCode" type="CS" minOccurs="1" maxOccurs="1"/>
         <xs:element name="acceptAckCode" type="CS" minOccurs="1" maxOccurs="1"/>
         <xs:element type="MCCI_MT010101UK12.CommunicationFunctionRcv" minOccurs="1" maxOccurs="unbounded" name="communicationFunctionRcv"/>
         <xs:element type="MCCI_MT010101UK12.CommunicationFunctionSnd" minOccurs="1" maxOccurs="1" name="communicationFunctionSnd"/>
         <xs:element name="ControlActEvent" type="RCMR_IN030000UK06.ControlActEvent"/>
      </xs:sequence>
      <xs:attribute name="type" type="Classes" default="Message"/>
      <xs:attribute name="typeID" use="optional">
         <xs:simpleType>
            <xs:list itemType="oid"/>
         </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="realmCode" use="optional">
         <xs:simpleType>
            <xs:list itemType="cs"/>
         </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="nullFlavor" type="cs" use="optional"/>
   </xs:complexType>
   <xs:complexType name="RCMR_IN030000UK06.ControlActEvent">
      <xs:sequence>
         <xs:element type="MCAI_MT040101UK03.Author" minOccurs="0" maxOccurs="1" name="author"/>
         <xs:element type="MCAI_MT040101UK03.Author2" minOccurs="1" maxOccurs="2" name="author1"/>
         <xs:element type="MCAI_MT040101UK03.Reason" minOccurs="0" maxOccurs="unbounded" name="reason"/>
         <xs:element name="subject" type="RCMR_IN030000UK06.Subject"/>
      </xs:sequence>
      <xs:attribute name="type" type="Classes" default="ControlAct"/>
      <xs:attribute name="classCode" type="ActClass" use="optional" default="CACT"/>
      <xs:attribute name="moodCode" type="ActMood" use="optional" default="EVN"/>
      <xs:attribute name="typeID" use="optional">
         <xs:simpleType>
            <xs:list itemType="oid"/>
         </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="realmCode" use="optional">
         <xs:simpleType>
            <xs:list itemType="cs"/>
         </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="nullFlavor" type="cs" use="optional"/>
   </xs:complexType>
      
         
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
      
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   <xs:complexType name="RCMR_IN030000UK06.Subject">
      <xs:sequence>
         <xs:element name="EhrExtract" type="RCMR_MT030101UK04.EhrExtract"/>
      </xs:sequence>
      <xs:attribute name="type" type="Classes" default="ActRelationship"/>
      <xs:attribute name="typeCode" type="ActRelationshipType" use="optional" default="SUBJ"/>
      <xs:attribute name="contextConductionInd" type="bl" use="optional" default="false"/>
      <xs:attribute name="typeID" use="optional">
         <xs:simpleType>
            <xs:list itemType="oid"/>
         </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="realmCode" use="optional">
         <xs:simpleType>
            <xs:list itemType="cs"/>
         </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="nullFlavor" type="cs" use="optional"/>
   </xs:complexType>
      
         
         
         
         
         
         
         
         
         
      
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
         
         
         
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
         
         
         
         
         
         
      
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
         
         
         
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
         
         
         
         
         
         
         
         
         
      
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
         
         
         
      
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
         
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
         
         
      
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
      
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
            
            
            
            
            
            
            
            
            
         
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
      
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
         
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
         
      
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
         
      
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
      
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
         
         
         
         
         
         
      
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
      
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
         
         
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
      
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
         
         
            
            
            
            
            
            
            
            
            
         
      
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
         
         
         
         
         
         
      
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
         
         
         
         
         
         
         
         
         
         
         
         
      
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
      
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
         
         
         
         
         
         
         
         
         
         
         
         
         
      
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
         
         
      
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
            
            
            
            
         
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
         
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
      
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
         
         
         
         
         
         
         
         
         
         
      
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
      
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
         
         
         
         
         
         
         
      
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
         
         
         
         
         
         
         
         
      
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
         
         
         
         
         
         
         
         
      
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
      
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
         
         
         
         
         
         
         
         
         
      
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
      
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
         
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
         
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
      
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
         
      
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
         
         
         
         
         
         
         
         
         
         
         
         
      
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
         
         
         
         
         
         
         
         
         
         
         
      
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
         
         
         
         
         
         
         
         
         
         
         
         
         
      
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
         
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
      
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
      
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
      
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
         
         
      
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
         
      
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
         
         
      
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
         
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   
      
      
      
      
         
            
         
      
      
         
            
         
      
      
   </xs:schema>

=== NHSDigital/integration-adaptor-gp2gp/service/src/test/resources/ehr/mapper/expected-output-message-wrapper.xml
<?xml version="1.0" encoding="UTF-8"?>
<RCMR_IN030000UK06 xmlns="urn:hl7-org:v3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:schemaLocation="urn:hl7-org:v3 ..\Schemas\RCMR_IN030000UK06.xsd">
    <id root="394559384658936"/>
    <creationTime value="20200218170946"/>
    <versionCode code="V3NPfIT3.1.10"/>
    <interactionId root="2.16.840.1.113883.2.1.3.2.4.12" extension="RCMR_IN030000UK06"/>
    <processingCode code="P"/>
    <processingModeCode code="T"/>
    <acceptAckCode code="NE"/>
    <communicationFunctionRcv typeCode="RCV">
        <device classCode="DEV" determinerCode="INSTANCE">
            <id root="1.2.826.0.1285.0.2.0.107" extension="from-asid-value"/>
        </device>
    </communicationFunctionRcv>
    <communicationFunctionSnd typeCode="SND">
        <device classCode="DEV" determinerCode="INSTANCE">
            <id root="1.2.826.0.1285.0.2.0.107" extension="to-asid-value"/>
        </device>
    </communicationFunctionSnd>
    <ControlActEvent classCode="CACT" moodCode="EVN">
        <author1 typeCode="AUT">
            <AgentSystemSDS classCode="AGNT">
                <agentSystemSDS classCode="DEV" determinerCode="INSTANCE">
                    <id root="1.2.826.0.1285.0.2.0.107" extension="to-asid-value"/>
                </agentSystemSDS>
            </AgentSystemSDS>
        </author1>
        <subject typeCode="SUBJ" contextConductionInd="false">
            <EhrExtract classCode="EXTRACT" moodCode="EVN">
                <id root="12345"/>
            </EhrExtract>
        </subject>
    </ControlActEvent>
</RCMR_IN030000UK06>
